#piece is under attack
#UNDERATTACKTRUE = 3
#UNDER_ATTACK_BUT_DEFENDED = 1

#piece to take values
HANGINGPIECE = 5
EQUALTRADE = 1

#moving into danger
MOVEINTODANGERTRUE = -5
MOVEINTODANGERFALSE = 0.1

#MOVE THEORY

#KING
CASTLINGWEIGHT = 2
KINGMOVE = - 0.5 #generally we dont want king to move

#BISHOP
FIANCHETTO_VALUE = .3 #small boost to encourage fianchettoing
STANDARD_BISHOP_SPOT = .2
BISHOP_NOT_MOVED = .2

#ROOK
ROOK_NOT_MOVED = -.5

#KNIGHT
KNIGHT_NOT_MOVED = .25

#PAWN
FIANCHETTO_VALUE = .2
CENTRAL_PAWN_VALUE = .3
SIDE_PAWN_VALUE = .15
PAWN_CHAIN_VALUE = .3
PASSED_PAWN_VALUE = .8
PAWN_PROMOTION = 2
KING_PAWN_VALUE = -.2

#QUEEN
QUEEN_NOT_MOVED = -.4